version: "3.9"

services:

  wordpress:
    depends_on:
      wpdb:
        condition: service_healthy
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/everything-all-of-the-time
    ports:
      - "6000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  wpdb:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

  wpcli:
    image: wordpress:cli
    depends_on:
      wpdb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/everything-all-of-the-time
      - ./db:/var/www/html/db
    environment:
      WORDPRESS_DB_HOST: wpdb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      ABSPATH: /usr/src/wordpress/

  phpunit:
    image: futureys/phpunit-wordpress-plugin
    depends_on:
      testwpdb:
        condition: service_healthy
    command:
      - bash
    depends_on:
      - testwpdb
    environment:
      DATABASE_PASSWORD: examplepass
      DATABASE_HOST: testwpdb
    stdin_open: true
    tty: true
    volumes:
      - ./:/plugin

  testwpdb:
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    image: mariadb:10.5.8
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
volumes:
  db_data: {}
  wordpress_data: {}
