# Based on https://github.com/wp-cli/scaffold-command/blob/f9bad3dd7224d5684d950d31c486df70905e386f/templates/plugin-github.mustache
name: WordPress Tests

on: [push]

env:
  WP_TESTS_DIR: /github/home/wp-tests/wordpress-tests-lib
  WP_CORE_DIR: /github/home/wp-tests/wordpress

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        wordpress-version: [ latest ]
    container:
      image: junaidbhura/wp-tests:php-${{ matrix.php-version }}
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      ## Setup composer
      - name: Install Composer dependencies
        run: |
          composer install --no-dev
          composer require yoast/phpunit-polyfills
          composer global require "phpunit/phpunit=6.1.0"

      # Build JavaScript to prevent errors.
      - name: Install and build JavaScript
        run: |
          npm install
          npm run build

      ## Install WordPress Test Suite
      - name: Install WordPress test suite
        run: bash bin/install-wp-tests.sh wordpress_test root root mysql ${{ matrix.wordpress-version }}

      ## Run the tests
      - name: Tests
        run: $HOME/.composer/vendor/bin/phpunit --config=phpunit-integration.xml
