# Based on https://github.com/wp-cli/scaffold-command/blob/f9bad3dd7224d5684d950d31c486df70905e386f/templates/plugin-github.mustache
name: WordPress Tests

on: [push]

env:
  WP_TESTS_DIR: /github/home/wp-tests/wordpress-tests-lib
  WP_CORE_DIR: /github/home/wp-tests/wordpress

jobs:

  test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      ## Setup composer
      - name: Install Composer dependencies
        run: |
          composer install

      ## Run the tests
      - name: Tests
        run: |
          docker-compose up -d
          docker-compose phpunit
          composer install
          composer test:wordpress
